name: Build and deploy JAR app to Azure Web App - board-api-service

on:
  push:
    branches:
      - master  # 또는 master (실제 브랜치명에 맞게 수정)
    paths:
      - 'board-api/**'  # board-api 폴더 변경시만 트리거
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '8'  # Java 8 
          distribution: 'zulu'  # 11일경우 Eclipse Temurin
      
      - name: Build with Maven
        run: |
          cd board-api  # 서브폴더로 이동
          mvn clean package -DskipTests
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'board-api/target/*.jar'  # 올바른 경로 지정

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_96CE7299F725402FB8CB7412A5900596 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA891B9712464031B783A8500645BAF2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_75A9EDDFEEAE45BC810D5CD97ADAA97C }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'board-api-service'
          slot-name: 'Production'
          package: '*.jar'

      # - name: Health Check
      #   run: |
      #     echo "애플리케이션 시작 대기 중..."
      #     sleep 60
          
      #     echo "헬스체크 시작..."
      #     for i in {1..10}; do
      #       if curl -f -s https://board-api-service.azurewebsites.net/actuator/health > /dev/null 2>&1; then
      #         echo "헬스체크 성공! (시도 $i)"
      #         exit 0
      #       else
      #         echo "헬스체크 실패, 재시도 중... (시도 $i/10)"
      #         sleep 30
      #       fi
      #     done
          
      #     echo "헬스체크 최종 실패"
      #     exit 1


##############################################
# name: Build and deploy JAR app to Azure Web App - board-api-service

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Java version
#         uses: actions/setup-java@v4
#         with:
#           java-version: '8'
#           distribution: 'microsoft'

#       - name: Build with Maven
  #       run: mvn clean install

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: java-app
  #         path: '${{ github.workspace }}/target/*.jar'

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   permissions:
  #     id-token: write #This is required for requesting the JWT
  #     contents: read #This is required for actions/checkout
  
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: java-app
      
  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_96CE7299F725402FB8CB7412A5900596 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA891B9712464031B783A8500645BAF2 }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_75A9EDDFEEAE45BC810D5CD97ADAA97C }}

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: 'board-api-service'
  #         slot-name: 'Production'
  #         package: '*.jar'
          
